version: '3.8'
services:
  zookeeper:
    container_name: zookeeperContainer
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - semester6project_network

  kafka-manager:
      container_name: kafkaManagerContainer
      image: hlebalbau/kafka-manager:stable
      ports:
        - "9000:9000"
      environment:
        ZK_HOSTS: "zookeeperContainer:2181"
      networks:
        - semester6project_network

  kafka:
    container_name: kafkaContainer
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperContainer:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaContainer:9092,PLAINTEXT_HOST://kafkaContainer:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - semester6project_network

  kafka2:
    container_name: kafkaContainer2
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeperContainer:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaContainer2:9093,PLAINTEXT_HOST://kafkaContainer2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - semester6project_network

  kafka3:
    container_name: kafkaContainer3
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeperContainer:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaContainer3:9094,PLAINTEXT_HOST://kafkaContainer3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - semester6project_network

  projectservice:
    container_name: projectservicecontainer
    image: ghcr.io/mitchell2001b/projectservice:main
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://project-db:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}
    networks:
      - semester6project_network
    depends_on:
      - project-db

  project-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_DOCKER_PORT}:${MYSQLDB_LOCAL_PORT}"
    networks:
      - semester6project_network

  taskboarding-frontend:
    container_name: taskboarding-frontend
    image: ghcr.io/mitchell2001b/taskboardingfrontend:main
    build:
      context: ../TaskboardingFrontend
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    networks:
      - semester6project_network

  api-gateway:
    container_name: apigateway
    image: ghcr.io/mitchell2001b/apigateway:main
    env_file:
      - ../apigateway/.env
    build:
      context: ../ApiGateway
    ports:
      - "${GATEWAY_LOCAL_PORT}:${GATEWAY_DOCKER_PORT}"
    networks:
      - semester6project_network

  redis:
    container_name: redisContainer
    image: redis:7.2.3
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}"
    networks:
      - semester6project_network

networks:
  semester6project_network:
    name: semester6project_network
    driver: bridge